### DISCUSSION TITLE
Em medidas no Layout em qual momento ideal para ser utilizado cm, mm, em, % ou pc.

### DISCUSSION THREAD

**Discussion by Marcelosilva10** [frontendbr/forum#141] [Perguntas e Respostas]
Galera primeiramente tenham uma ótima semana sei que aqui existe só ninjas no Front minha pergunta e o seguinte qual é o momento ideal para utilizar Px, cm, mm, em, % ou pc e tem regras para ser usado isso tem alguma forma padrão ou depende de como o dev trabalha?

**Comment by charbelrami** [comment]
Olá,
Para simplificar, IMHO:
- Evite unidades físicas absolutas, como **cm**, **mm**, **in**, **pt**, etc.
- Use unidades relativas ao tamanho da fonte, principalmente **em** e **rem**.
- Use unidades relativas ao viewport (dimensões do bloco recipiente inicial), principalmente **vw** e **vh**.

Use **%** para evitar ajustes automáticos no tamanho da fonte ao mudar a orientação do dispositivo (IE, iOS):

``` css
html {
  -ms-text-size-adjust: 100%;
  -webkit-text-size-adjust: 100%;
}
```

ou quando você quer que um elemento ocupe, no máximo, 100% da largura de seu recipiente (elementos podem ultrapassar a largura de seus recipientes, quebrando o layout):

``` css
.el {
    max-width: 100%;
}
```

Use **px** para o tamanho inicial da fonte,

``` css
:root {
    font-size: 14px;
}
```

para altura de elementos

``` css
.btn {
    height: 30px;
}
```

e para margins e paddings.

``` css
.cont {
    margin: 0 16px;
    padding: 16px;
}
```

Use **vw** para definir largura de elementos, fazendo-os responsivos. Evite **px**.

``` css
.cont {
    width: 90vw;
}
```

Para variações no tamanho da fonte relativas ao tamanho inicial, use **rem**:

``` css
h1 {
    font-size: 1.5rem;
}
```

Use **em** para breakpoints em media queries

``` css
@media (min-width: 48em) {
}
```

ou para variações no tamanho da fonte relativas ao recipiente:

``` css
small {
    font-size: .75em;
}
```

Use **vh** em casos como:

``` css
.section--fit {
    min-height: 100vh;
}
```

No exemplo acima, quero que o elemento ocupe, no mínimo, toda a altura do viewport.

``` css
.section--half {
    height: 50vh;
}
```

No exemplo acima, quero que o elemento ocupe metade da altura do viewport.
