### DISCUSSION TITLE
Canvas e SEO

### DISCUSSION THREAD

**Discussion by abnersajr** [frontendbr/forum#171] [Perguntas e Respostas]
Estou desenvolvendo um projeto para um fotógrafo e novamente o designer inventou uma moda que num so dos mais fãs, mas dessa vez é necessário e não tem escapatória.
Hover de imagem em `grayscale`. O site é responsivo então precisaria utilizar `background-size: cover` ai procura daqui dali achei uma solução mas não funciona o `cover` então acabei optando por usar Canvas.

Gostaria de saber se alguém já teve alguma experiência em que usou Canvas e como ficou o SEO, existe alguma coisa do tipo microdata e etc para isso, digo referenciar que aquele canvas é uma imagem seia lá.

**Comment by kazzkiq** [comment]
Cara, se você não tiver problemas com navegadores muito antigos, dá pra usar CSS3 e gerar a imagem em _grayscale_ sem usar Canvas.

Exemplo:

``` css
.gray-img:hover {
    -webkit-filter: grayscale(1);
    -moz-filter: grayscale(1);
    -ms-filter: grayscale(1);
    filter: grayscale(1);
}
```

Sei que essa solução não ataca a sua pergunta propriamente dita, mas as vezes já resolveria de forma mais simples.

Funciona em todos os navegadores **menos nos IEs (8, 9, 10 e 11)**. No caso desses navegadores você pode usar uma das soluções descritas nesses links:

http://stackoverflow.com/questions/609273/convert-an-image-to-grayscale-in-html-css
http://stackoverflow.com/questions/14813142/internet-explorer-10-howto-apply-grayscale-filter
