### DISCUSSION TITLE
Efeito ao passar mouse sobre imagem

### DISCUSSION THREAD

**Discussion by jcvilanova** [frontendbr/forum#2296] [Perguntas e Respostas] [answered]
Galera, alguém sabe como se faz esse efeito de quando se passa o mouse sobre o card, como o que vi nesta página :

https://www.ryazbek.com.br/  e o que está nessa tambem https://demo.athemes.com/sydney/

 

alguém poderia explicar por favor como se faz isso ? Gostaria de fazer isso no meu site

**Comment by felquis** [comment, marked as answer]
Seria algo assim:

```css
.title {
  background: white;
  opacity: 0;
  transform: traslateY(-1rem);
  transition: opacity transform;
}

.card:hover .title {
  opacity: 1;
  transform: translateY(0rem);
}
```

Veja se te ajuda a ter uma base de como pode ser feito.
