### ISSUE TITLE
Modificadores no BEM

### ISSUE THREAD

**Issue by theandersonn** [frontendbr/forum#1041]
Estou um pouco encucado com a utilização de modificadores no BEM, a questão é que a declaração está ficando grande no html.

Exemplo:

```css
.caixa-principal {
    &--verde { background-color: green; }
    &--borda { border: 1px solid #000; }
}

<div class="caixa-principal caixa-principal--verde caixa-principal--borda">
lorem ipsum
</div>
```

Como vcs fazem?  Alguma sugestão para melhorar a legibilidade?
