### ISSUE TITLE
Botões com `cursor: pointer;` x Acessibilidade

### ISSUE THREAD

**Issue by filipelinhares** [frontendbr/forum#212]
Fala pessoal.

Rolou uma [discussão](https://github.com/filipelinhares/ress/issues/4) por aqui sobre aplicar `cursor pointer` em todos os botões:

```css
[type="button"],
[type="reset"],
[type="submit"]
[role="button"] {
  cursor: pointer;
}

[disabled] {
  cursor: default;
}
```

O Normalize tinha isso, porem foi [removido](https://github.com/necolas/normalize.css/pull/563) depois desse comentário:

> Web browsers are fairly consistent:
> - Buttons are `cursor: default`;
> - Links are `cursor: pointer`.
> 
> The concept for links is that they take you to a different URL. The hand cursor (pointer) indicates that. Buttons don't take you to a different URL (with the notable exception of form submit buttons, though this is less true with scripted or HTML5-validated forms), and thus don't have this style.

> ## Specification
> pointer: The cursor is a pointer that indicates a link.
>
> http://www.w3.org/TR/CSS21/ui.html#cursor-props
> http://dev.w3.org/csswg/css-ui/#cursor

_comentário: https://github.com/necolas/normalize.css/issues/371#issuecomment-60072171_

Gostaria da opinião de vocês. Alguém algum dia NÃO precisou de cursor pointer em um botão?
