### ISSUE TITLE
Classe atrelada ao estilo? 

### ISSUE THREAD

**Issue by ghost** [frontendbr/forum#215]
Tenho vários elementos que terão partes com estilos similares, qual é a forma mais correta de se escrever o CSS?

Agrupando os seletores:

``` css
.hero,
.contact {
    display: flex;
}
```

Usando uma classe separada:

``` css
.flex {
    display: flex;
}
.hero {
    ...
}
.contact {
    ...
}
```

Na primeira forma, agrupar todas as classes que irão ter a mesma propriedade.
Na segunda forma, criar uma classe atrelada ao estilo e aplicar no HTML.

Bom, vejo várias pessoas dizendo que isso é errado, mas também vejo muitas pessoas usando classes no HTML como: .no-margin, .no-padding, .text-center, mesmo sem usar Bootstrap.

Eai?

**Comment by barbier** [comment]
Eu não vejo problema em nomear classes de acordo com o papel delas no layout ou a funcionalidade delas, infelizmente não lembro onde li que são semânticas de nome diferentes.....
Acho que isso deve entrar em acordo com o time mesmo.

**Comment by keitoliveira** [comment]
Nada é escrito na pedra, a menos que cause um grande problema, não é errado escrever classes agrupadas.

Costumo usar classes agrupadas quando meus elementos não usam classes globais mas tem propriedades em comum com outras classes em X contexto. Um bom exemplo, uma página:

```css
.page-element-1,
.page-element-2 {
   display: [...];
   font: [...];
   padding: [...];
   margin: [...];
   color: [...];
}

.page-element-1 {
   justify-content: center;
   [...]
}

.page-element-2 {
  justify-content: space-between;
  [...]
}
```
```html
<div class="page-element-1"></div>
<div class="page-element-2"></div>
```

Isso poderia ser usado dessa forma também:

```css
.page-element {
   display: [...];
   font: [...];
   padding: [...];
   margin: [...];
   color: [...];
}

.page-element-1 {
   justify-content: center;
   [...]
}

.page-element-2 {
  justify-content: space-between;
  [...]
}
```

```html
<div class="page-element page-element-1"></div>
<div class="page-element page-element-2"></div>
```

Mas se a classe não é global, não acho que seja o melhor caminho.

Agora, se meu elemento precisa de propriedades de uma class global e ainda assim, é necessário complementar:

```css
.section-group {
   display: [...];
   font: [...];
   padding: [...];
   margin: [...];
   color: [...];
}

.page-element-1 {
   justify-content: center;
   [...]
}

.page-element-2 {
  justify-content: space-between;
  [...]
}
```

```html
<div class="section-group page-element-1"></div>
<div class="section-group page-element-2"></div>
```

Sem crise.

Como eu disse, nada é escrito na pedra mas é preciso uma analise antes de sair escrevendo para evitar coisas como:

```html
<div class="class-1 class-2 class-3 class-4 class-5 class-6 class-7"></div>
```

ou

![screenshot 2016-07-07 14 13 30](https://cloud.githubusercontent.com/assets/3808430/16662263/02ae4bda-444d-11e6-87e6-d75c83ce2c85.png)

rs rs rs
