### ISSUE TITLE
Maneiras de fazer um ARC/Ellipse com SVG/CSS/HTML para a Web?

### ISSUE THREAD

**Issue by felquis** [frontendbr/forum#705]
Olá pessoal, eu nunca fiz algo deste tipo:

![image](https://user-images.githubusercontent.com/736728/29997667-7b6ab59c-8fef-11e7-8b00-6c3cbb4fee7a.png)

Usei o path com o [Elliptical Arc Commands](https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands), e consegui um resultado aproximado usando o [stroke-dasharray e stroke-dashoffset](https://css-tricks.com/svg-line-animation-works/) do CSS/SVG.

```css
.progress path {
  stroke-dasharray: 260px;
  stroke-dashoffset: calc(260px / 2);
}
```
https://codepen.io/felquis/pen/xLMoaN porém o resultado parece ser bem... opinionado na implementação, assim como tudo na Web tem mais maneiras de fazer a mesma coisa.

É isso ai, vocês conhecem alguma outra maneira de chegar neste resultado? Até mais! Espero aprender com este tópico! :D
