### ISSUE TITLE
Seguindo o "mobile-first concept", é ideal dar preferência para o `max-width` ou `min-width` no CSS?

### ISSUE THREAD

**Issue by StanleySathler** [frontendbr/forum#793]
Olá pessoal, tudo bem?

Muitos já conhecem o conceito de "mobile first". Conceito este que eu tento seguir em minhas aplicações faz um certo tempo.

Desde que comecei a tentar aplicar a ideia, eu sempre dei preferência para o uso do `min-width` em minhas media-queries (CSS). Ou seja, eu sempre tentei escrever um CSS todo pensando - e testando - no mobile e, na hora de partir para o desktop, sempre que necessário o uso de media-query, eu usava o `min-width` para sobrescrever alguma informação.

O problema é que toda propriedade CSS tem um valor padrão, certo!? Muitas vezes, na hora de escrever o CSS para mobile, eu colocava um valor não-padrão em determinada propriedade. Na hora de passar para desktop, eu adicionava um novo valor para aquela propriedade que, de certa forma, já seria a padrão se eu não tivesse sobrescrito-a no mobile antes.

Um exemplo para ilustrar melhor:
```css
/* Supondo ser um SASS/Less, ok, pessoal!? Para simplificar */

.meu-componente {
  text-align: center; /* o padrão é left, correto? */

  @media (min-width: 1024px) {
    text-align: left; /* sobrescrevo de novo, agora para voltar ao padrão */
  }
}
```

Nesse caso eu poderia, claro, fazer:
```css
.meu-componente {
  @media (max-width: 1023px) {
    text-align: center;
  }
}
```

A segunda opção me traz, com o tempo, um CSS menos verboso e repetitivo.

Escrevendo o CSS desta maneira (segunda opção) eu estaria indo contra o conceito de "mobile-first" ou não tem nada a ver? 

Ter um CSS com vários `min-width` e `max-width` misturados é uma má prática (ou seja, deveria eu sempre optar por uma das opções na maioria dos casos) ou é normal, comum?

Agradeço de coração,
Stanley Sathler. ❤️
